baseurl = "https://aeas44.github.io/"
languageCode = "ja-jp"
title = "Learn to program"
# Enable comments by entering your Disqus shortname
# disqusShortname = "aeas44"
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
theme = "hugo-hikari-theme"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "aeas44"
	description = "Learn to program"
	copyright = "POWERED BY [HUGO](//gohugo.io) - THEME: [HIKARI](//github.com/digitalcraftsman/hugo-hikari-theme)"

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "Sorry, but the requested page wasn’t <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "計算機科学の勉強中"
	bio = "修行中"
	subscribe = "Subscribe"
	followme = "Follow me on"

	[[params.offcanvas.socialnetworks]]
		name = "Github"
		url = "//github.com/aeas44"

	[[params.offcanvas.socialnetworks]]
		name = "Twitter"
		url = "//twitter.com/aeas44"